enableVersioning: true
handle: home
name: home
propagationMethod: all
siteSettings:
  50e3e884-8ae1-4582-8237-f6efadfe0e6b:
    enabledByDefault: true
    hasUrls: true
    template: home
    uriFormat: __home__
type: single
